import SearchHeader from "@/components/SearchHeader";

export const metadata = {
    title: "Google",
    description: "Generated by create next app",
};

export default function SearchLayout({ children }) {
    return (
        <>
            <SearchHeader />
            <div>{children}</div>
        </>
    );
}
